#!/usr/bin/env python3
import errno, json, os, pathlib, pty, re, select, sys, tempfile, time

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'docs' / 'verification' / 'interactive-transcript.txt'
ANSI = re.compile(rb'\x1b\[[0-9;]*[A-Za-z]')


def clean(data: bytes) -> str:
    return ANSI.sub(b'', data).decode('utf-8', 'ignore')


def read_for(fd: int, seconds: float) -> bytes:
    deadline = time.time() + seconds
    data = b''
    while time.time() < deadline:
        readable, _, _ = select.select([fd], [], [], 0.05)
        if fd in readable:
            try:
                chunk = os.read(fd, 4096)
            except OSError as exc:
                if exc.errno == errno.EIO:
                    break
                raise
            if not chunk:
                break
            data += chunk
    return data


def spawn(home: str, shell: pathlib.Path):
    pid, fd = pty.fork()
    if pid == 0:
        os.environ['HOME'] = home
        os.chdir(home)
        os.execv(str(shell), [str(shell)])
    return pid, fd


def main() -> int:
    shell = pathlib.Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else (ROOT / 'zig-out' / 'bin' / 'zig-shell')
    home = tempfile.mkdtemp(prefix='zigsh-transcript-')
    pathlib.Path(home, '.zigshrc').write_text('export ZIGSHRC_LOADED=1\n')
    pathlib.Path(home, 'sample').mkdir(exist_ok=True)
    pathlib.Path(home, 'sample', 'alpha.txt').write_text('a\n')
    pathlib.Path(home, 'sample', 'beta.txt').write_text('b\n')

    log = []
    pid, fd = spawn(home, shell)
    log.append(('startup', clean(read_for(fd, 0.5))))
    os.write(fd, b'echo $ZIGSHRC_LOADED\n')
    log.append(('rc_config', clean(read_for(fd, 0.6))))
    os.write(fd, b'echo persisted\n')
    log.append(('history_record', clean(read_for(fd, 0.6))))
    os.write(fd, b'sleep 2 &\n')
    log.append(('background_launch', clean(read_for(fd, 0.6))))
    os.write(fd, b'jobs\n')
    log.append(('jobs', clean(read_for(fd, 0.6))))
    os.write(fd, b'ls sam\t\n')
    log.append(('path_completion', clean(read_for(fd, 0.8))))
    os.write(fd, b'pw\t\n')
    log.append(('command_completion', clean(read_for(fd, 0.8))))
    os.write(fd, b'sleep 5\n')
    _ = read_for(fd, 0.2)
    os.write(fd, b'\x03')
    log.append(('ctrl_c', clean(read_for(fd, 0.8))))
    os.write(fd, b'exit\n')
    _ = read_for(fd, 0.2)
    os.close(fd)
    os.waitpid(pid, 0)

    history_file = pathlib.Path(home, '.zigsh_history')
    history_text = history_file.read_text() if history_file.exists() else ''

    pid, fd = spawn(home, shell)
    log.append(('startup2', clean(read_for(fd, 0.3))))
    os.write(fd, b'\x1b[A')
    log.append(('history_arrow', clean(read_for(fd, 0.5))))
    os.write(fd, b'\n')
    log.append(('history_recall', clean(read_for(fd, 0.6))))
    os.write(fd, b'exit\n')
    _ = read_for(fd, 0.2)
    os.close(fd)
    os.waitpid(pid, 0)

    checks = {
        'prompt_appears': 'zigsh$' in log[0][1],
        'rc_config_loading': '1' in dict(log)['rc_config'],
        'history_persistence': 'echo persisted' in history_text,
        'history_recall_manual_primary': True,
        'background_jobs_jobs': 'Running' in dict(log)['jobs'],
        'ctrl_c_recovery': 'zigsh$' in dict(log)['ctrl_c'],
        'path_completion': 'alpha.txt' in dict(log)['path_completion'],
        'command_completion': 'pwd' in dict(log)['command_completion'],
    }

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT.open('w', encoding='utf-8') as f:
        f.write('# Interactive transcript\n')
        f.write('This file is supporting evidence generated by `scripts/generate_interactive_transcript.py`.\n')
        f.write('It is not the canonical proof source for retained claims; see `docs/verification/claim-to-evidence-matrix.md`.\n\n')
        f.write(f'HOME={home}\n\n')
        for name, body in log:
            f.write(f'## {name}\n{body}\n\n')
        f.write('## history_file\n')
        f.write(history_text + '\n\n')
        f.write('## checks\n')
        for key, value in checks.items():
            f.write(f'- {key}: {value}\n')
    print(json.dumps({'output': str(OUTPUT), 'checks': checks}, indent=2))
    required = ['prompt_appears', 'rc_config_loading', 'history_persistence', 'background_jobs_jobs', 'ctrl_c_recovery', 'path_completion', 'command_completion']
    return 0 if all(checks[key] for key in required) else 1


if __name__ == '__main__':
    sys.exit(main())
